# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3a2bf5f152861dba209c58ee7f92ae5"
name = "HRAN-DASHBOARD"
application_url = "https://sublime-edges-current-sister.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://sublime-edges-current-sister.trycloudflare.com/auth/callback", "https://sublime-edges-current-sister.trycloudflare.com/auth/callback/online", "https://sublime-edges-current-sister.trycloudflare.com/api/auth/callback" ]
