name: Guard Canonical Files

on: [push]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure canonical instruction files exist
        run: |
          missing=0
          for file in \
            docs/NORTH_STAR.md \
            docs/COMPONENTS.md \
            docs/PATTERNS.md \
            docs/TROUBLESHOOTING.md \
            docs/ARCHITECTURE.md \
            docs/DECISIONS.md \
            plans/rpg.json \
            plans/tasks.backlog.yaml \
            agent_launch_commands.md; do
            if [ ! -e "$file" ]; then
              echo "::error::Missing required file $file"
              missing=1
            fi
          done
          # Require at least one cleanup inventory doc for the current repo state
          if ! ls docs/cleanup/inventory-*.md >/dev/null 2>&1; then
            echo "::error::Missing cleanup inventory (docs/cleanup/inventory-YYYYMMDD.md)"
            missing=1
          fi
          exit $missing
