name: RAG Refresh

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -U llama-index openai "chromadb>=0.5" llama-index-vector-stores-chroma llama-index-readers-web llama-index-readers-file pyyaml llama-index-embeddings-fastembed fastembed
      - name: Bootstrap ingest
        env:
          RAG_FORCE_MOCK_EMBED: "1"
        run: python ingest_site_chroma.py
      - name: Incremental ingest
        env:
          RAG_FORCE_MOCK_EMBED: "1"
        run: python ingest_incremental_chroma.py
      - name: Golden tests
        env:
          OFFLINE_CORRECTIONS_ONLY: "1"
          RAG_FORCE_MOCK_EMBED: "1"
        run: python run_goldens.py
