name: verify-managed-files
on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Block non-manager edits to managed files
        run: |
          MANAGED='^(docs/(NORTH_STAR\.md|COMPONENTS\.md|PATTERNS\.md|TROUBLESHOOTING\.md|ARCHITECTURE\.md|DECISIONS\.md|cleanup/)|plans/rpg\.json|plans/tasks\.backlog\.yaml|plans/agents/[^/]+/direction\.md|feedback/[^/]+\.md|agent_launch_commands\.md)'
          if git diff --name-only origin/${{ github.base_ref }}... | grep -E "$MANAGED" >/dev/null; then
            if [ "${{ github.actor }}" != "Jgorzitza" ]; then
              echo "❌ Non-manager actor ${{ github.actor }} attempted to modify managed files."
              exit 1
            fi
          fi
      - name: Ensure canonical docs exist
        run: |
          missing=0
          for file in docs/NORTH_STAR.md docs/COMPONENTS.md docs/PATTERNS.md docs/TROUBLESHOOTING.md docs/ARCHITECTURE.md docs/DECISIONS.md plans/rpg.json plans/tasks.backlog.yaml agent_launch_commands.md; do
            if [ ! -e "$file" ]; then
              echo "::error::Missing required file $file"
              missing=1
            fi
          done
          exit $missing
